coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("users.urls")),
    path("admin/", admin.site.urls),
    path("products/", include("products.urls")),
    path("orders/", include("orders.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
# # from django.contrib import admin
from django.urls import path
from .views import OrderView, CreateOrder

urlpatterns = [
    path("my-orders/", OrderView.as_view(), name="my_orders"),
    path("create-order/", CreateOrder, name="create_order"),
]

products/urls.py
# from django.contrib import admin
from django.urls import path
from .views import ProductListView, ProductFormView, ProductListApi

urlpatterns = [
    path("", ProductListView.as_view(), name="list_product"),
    path("add/", ProductFormView.as_view(), name="add_product"),
    path("api/", ProductListApi.as_view(), name="api_list_products"),
]

users/urls.py
# from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView

urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product

# Create your models here.


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    order_date = models.DateTimeField(auto_now=True)
    table_number = models.IntegerField()

    def __str__(self):
        return f"Order {self.id} by {self.user} to table #{self.table_number}"


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.order} - {self.product}"

products/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    name = models.TextField(max_length=250, verbose_name="nombre")
    description = models.TextField(max_length=500, verbose_name="descripción")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="precio")
    avaible = models.BooleanField(default=True, verbose_name="disponible")
    photo = models.ImageField(
        upload_to="logos", null=True, blank=True, verbose_name="foto"
    )

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.Form):
    name = forms.CharField(max_length=250, label="Nombre")
    description = forms.CharField(
        max_length=500, widget=forms.Textarea(attrs={"rows": "3"}), label="Descripción"
    )
    price = forms.DecimalField(max_digits=10, decimal_places=2, label="Precio")
    avaible = forms.BooleanField(initial=True, label="Disponible", required=False)
    photo = forms.ImageField(label="Foto", required=False)

    def save(self):
        Product.objects.create(
            name=self.cleaned_data["name"],
            description=self.cleaned_data["description"],
            price=self.cleaned_data["price"],
            avaible=self.cleaned_data["avaible"],
            photo=self.cleaned_data["photo"],
        )

orders/views.py
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.views.generic import DetailView
from .models import Order, OrderProduct
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import JsonResponse
import json

# Create your views here.


class OrderView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = "orders/my_orders.html"
    context_object_name = "order"

    def get_object(self, queryset=None):
        return Order.objects.filter(is_active=True, user=self.request.user)


def CreateOrder(request):
    if request.method == "POST":
        try:
            # Obtener y parsear el cuerpo de la solicitud como JSON
            data = json.loads(request.body)

            # Obtener el número de la mesa
            table_number = data.get("table_number")

            if not table_number:
                return JsonResponse(
                    {"status": "failed", "message": "Table number is required"},
                    status=400,
                )

            # Obtener el usuario (asegúrate de que el usuario esté autenticado)
            user = request.user

            # Crear la orden
            order = Order.objects.create(user=user, table_number=table_number)

            # Obtener los productos y cantidades
            products = data.get("products", [])

            if not products:
                return JsonResponse(
                    {"status": "failed", "message": "No products provided"}, status=400
                )

            for product_data in products:
                product_id = product_data.get("product")
                quantity = product_data.get("quantity")

                if not product_id or quantity is None:
                    return JsonResponse(
                        {
                            "status": "failed",
                            "message": "Product ID and quantity are required",
                        },
                        status=400,
                    )

                # Crear la relación OrderProduct
                OrderProduct.objects.create(
                    order=order, product_id=product_id, quantity=quantity
                )

            return JsonResponse({"status": "success", "order_id": order.id})

        except json.JSONDecodeError:
            return JsonResponse(
                {"status": "failed", "message": "Invalid JSON"}, status=400
            )

    return JsonResponse(
        {"status": "failed", "message": "Invalid request method"}, status=405
    )

products/views.py
from django.views import generic
from django.views.generic.base import TemplateView
from .forms import ProductForm
from django.urls import reverse_lazy
from .models import Product
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework.views import APIView
from .serializers import PuductSerializer
from rest_framework.response import Response


class ProductFormView(LoginRequiredMixin, generic.FormView):
    template_name = "products/add_product.html"
    form_class = ProductForm
    success_url = reverse_lazy("list_product")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ProductListView(LoginRequiredMixin, TemplateView):
    template_name = "products/list.html"

    def get_context_data(self):

        product_list = Product.objects.all

        return {"products": product_list}


class ProductListApi(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request):
        products = Product.objects.all()
        serializer = PuductSerializer(products, many=True)

        return Response(serializer.data)

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy

# Create your views here.


class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("login")

orders/templates/orders/my_orders.html
{% extends 'base.html' %}
{% block title %}
  My Orders
{% endblock %}
{% block content %}
  <div class="row p-4">
    <div class="col-12">
      {% for order in order %}
        <div class="accordion" id="accordionExample">
          <div class="accordion-item">
            <h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">#{{ order.table_number }} - {{ order.user.username }} - {{ order.order_date }}</button></h2>
            <div id="collapse{{ order.id }}" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <div class="responsive-table">
                  <table class="table table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Precio</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for product_order in order.orderproduct_set.all %}
                        <tr>
                          <td>{{ product_order.product.name }}</td>
                          <td>{{ product_order.quantity }}</td>
                          <td>{{ product_order.product.price }}</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

products/templates/products/add_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  Products
{% endblock %}
{% block content %}
  <div class="row p-4">
    <div class="col-12 mb-4 text-start">
      <a class="btn btn-outline-dark btn-sm" href="{% url 'list_product' %}">Regresar</a>
    </div>
    <div class="col-12 col-lg-7">
      <div class="card shadow-sm">
        <div class="card-header bg-dark text-white">Crear producto</div>
        <div class="card-body">
          <div class="row">
            <form action="{% url 'add_product' %}" method="POST">
              {% csrf_token %}
              <div class="col-12">{{ form|crispy }}</div>
              <div class="col-12 text-end">
                <button class="btn btn-outline-dark btn-sm" type="submit">Crear</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

products/templates/products/list.html
{% extends 'base.html' %}
{% block title %}
  Products
{% endblock %}
{% block content %}
  <div class="row p-4">
    <div class="col-12 mb-4 text-start">
      <a class="btn btn-outline-dark btn-sm" href="{% url 'add_product' %}">Crear producto</a>
      <button class="btn btn-outline-dark btn-sm" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
        Ver pedido <div class="badge text-bg-light" id="count-items">0</div>
      </button>
    </div>
    <div class="col-12">
      <div class="row d-flex justify-content-center">
        {% for product in products %}
          <div class="col-12 col-sm-6 col-md-4 col-xl-3 col-xxl-2 mb-4">
            <div class="card shadow-sm">
              {% if product.photo %}
                <img src="{{ product.photo.url }}" class="card-img-top" alt="{{ product.name }}" style="height: 150px; object-fit: cover;" />
              {% else %}
                <img src="https://picsum.photos/200/300" class="card-img-top" alt="{{ product.name }}" style="height: 150px; object-fit: cover;" />
              {% endif %}
              {% comment %} <img src="https://picsum.photos/200/300" class="card-img-top" alt="{{ product.name }}" style="height: 150px; object-fit: cover;" /> {% endcomment %}
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <div class="row">
                  <div class="col-12 text-secondary mb-1" style="font-size: small;">
                    <small>
                      <span id="short-description_{{ product.id }}">{{ product.description|slice:':50' }}...</span>
                      <span id="full-description_{{ product.id }}" style="display: none;">{{ product.description }}</span>
                      <a href="javascript:void(0);" onclick="toggleDescription({{ product.id }})" id="toggle-link_{{ product.id }}">Mostrar más</a>
                    </small>
                  </div>
                  <div class="col-12 mb-1">
                    <small>${{ product.price }}</small>
                  </div>
                  <div class="col-12 mb-1">
                    <small><div class="badge text-bg-{{ product.avaible|yesno:'success,warning' }}">{{ product.avaible|yesno:'Disponible,No disponible' }}</div></small>
                  </div>
                  <div class="col-12 text-end">
                    {% comment %} <button class="btn rounded-circle btn-outline-primary btn-sm"><i class="fa-regular fa-pen-to-square"></i></button> {% endcomment %}
                    <button class="btn rounded-circle btn-outline-dark btn-sm" onclick="AddProduct({{ product.id }}, '{{ product.name }}')"><i class="fa-solid fa-cart-plus"></i></button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasRightLabel">Pedido</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div class="row">
        <div class="col-12 mb-4">
          <div class="form-floating" id="table-input" style="display: none;">
            <input type="number" class="form-control" id="table"/>
            <label for=""># Mesa <b class="text-danger">*</b></label>
          </div>
        </div>
        <div class="col-12 mb-4">
          <ul class="list-group" id="list_products">
            <li class="list-group-item text-center border-0"><em>No hay productos agredados al pedido</em></li>
          </ul>
        </div>
        <div class="col-12 d-grid">
          <button class="btn btn-dark btn-sm" id="btn-create" style="display: none;" onclick="CreateOrder()">Crear pedido</button>
        </div>
      </div>
    </div>
  </div>

  <script>
    const btn_create = document.querySelector('#btn-create');
    const input_table = document.querySelector('#table-input');
    const count_items = document.querySelector('#count-items');
    const table = document.querySelector('#table');
    let Products = []

    const AddProduct = (id, name) => {
      if (Products.filter((e) => e.product_id == id).length > 0) {
        return Swal.fire({
          title: 'Información',
          text: 'El producto ya se encuentra agregado al pedido',
          icon: 'info',
          confirmButtonText: 'Cerrar'
        })
      }
      Products.push({ id: Date.now(), product_id: id, name: name, quantity: 1 });
      ListProducts();
      return Swal.fire({
        title: 'Información',
        text: 'El producto ha sido agregado',
        icon: 'success',
        confirmButtonText: 'Cerrar'
      })
    }

    function ListProducts(){
      const list_products = document.querySelector('#list_products');
      let html = '';
      Products.forEach((product) => {
        html += `
            <li class="list-group-item">
              <div class="row d-flex align-items-center">
                <div class="col-8 d-flex justify-content-start align-items-center px-0">
                  <button class="btn btn-link btn-sm" onclick="DeleteItem(${product.id})"><i class="fa-regular fa-trash-can"></i></button> ${product.name}
                </div>
                <div class="col-4 d-flex justify-content-end">
                  <small>
                    <div class="input-group">
                      <button class="btn btn-outline-secondary btn-sm" type="button" id="decrement" value='${product.id}' onclick='Decrement(${product.id})'>-</button>
                      <input type="text" class="form-control text-center" id='counter_${product.id}' value="${product.quantity}" readonly />
                      <button class="btn btn-outline-secondary btn-sm" type="button" id="increment" value='${product.id}' onclick="Increment(${product.id})">+</button>
                    </div>
                  </small>
                </div>
              </div>
            </li>
        `;
      });

      if(Products.length == 0){
        html = "<li class='list-group-item text-center border-0'><em>No hay productos agredados al pedido</em></li>";
        btn_create.style.display = "none";
        input_table.style.display = "none";
      } else {
        btn_create.style.display = "";
        input_table.style.display = "";
      }
      count_items.innerHTML = Products.length;
      list_products.innerHTML = html;
    }
    
    function toggleDescription(id) {
      var shortDesc = document.getElementById(`short-description_${id}`)
      var fullDesc = document.getElementById(`full-description_${id}`)
      var toggleLink = document.getElementById(`toggle-link_${id}`)
    
      if (shortDesc.style.display === 'none') {
        shortDesc.style.display = 'inline'
        fullDesc.style.display = 'none'
        toggleLink.textContent = 'Mostrar más'
      } else {
        shortDesc.style.display = 'none'
        fullDesc.style.display = 'inline'
        toggleLink.textContent = 'Mostrar menos'
      }
    }
    const Decrement = (id) =>{
      let counter = document.getElementById(`counter_${id}`)
      let value = parseInt(counter.value)
      if (value > 0) {
        counter.value = value - 1

        Products = Products.map(product => {
          if (product.id == id) {
              return {
                  ...product,
                  quantity: value - 1 
              };
          }
          return product; 
        });
      }
    }

    const Increment = (id) =>{
      let counter = document.getElementById(`counter_${id}`)
      let value = parseInt(counter.value)
      counter.value = value + 1

      Products = Products.map(product => {
        if (product.id == id) {
            return {
                ...product,
                quantity: value + 1
            };
        }
        return product; 
      });
    }

    const DeleteItem = (id) =>{
      Products = Products.filter((e) => e.id != id);
      ListProducts();
    }

    const CreateOrder = ()=>{
      if(table.value == "" || table.value < 0){
        return Swal.fire({
          title: 'Información',
          text: 'Es requerido el numero de la mesa del pedido',
          icon: 'info',
          confirmButtonText: 'Cerrar'
        })
      }

      let list_Product = [];
      Products.forEach((product) => {
        list_Product.push({product: product.product_id, quantity: product.quantity});
      });
      let Order = {
        "table_number" :table.value,
        "products" : list_Product
      }

      console.log(Order)
      const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      fetch('{% url "create_order" %}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': csrfToken  
        },
        body: JSON.stringify(Order)
      })
      .then(response => response.json())
      .then(data => {
          if (data.status === 'success') {
            Products = [];
            ListProducts();
            return Swal.fire({
              title: 'Información',
              text: 'Pedido creado exitosamente',
              icon: 'success',
              confirmButtonText: 'Cerrar'
            })
          } else {
              console.error('Failed to create order:', data.message);
          }
      })
      .catch(error => console.error('Error:', error));
      
    }
  </script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}

      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/fontawesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  </head>
  <body class="bg-light">
    <nav class="navbar navbar-expand-lg bg-body-tertiary shadow-sm border-bottom">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"><i class="fa-solid fa-mug-saucer fa-lg"></i></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            {% comment %} <a class="btn btn-outline-dark btn-sm border-0 {% if '/home/' in request.path %}active{% endif %}" aria-current="page" href="#"><i class="fa-solid fa-house"></i> Home</a> {% endcomment %}
            <a class="btn btn-outline-dark btn-sm border-0 mx-1 {% if '/my-orders/' in request.path %}active{% endif %}" href="{% url 'my_orders' %}"><i class="fa-solid fa-mug-hot"></i> My orders</a>
            <a class="btn btn-outline-dark btn-sm border-0 mx-1 {% if '/products/' in request.path %}active{% endif %}" href="{% url 'list_product' %}"><i class="fa-solid fa-mug-hot"></i> Products</a>
            {% if user.is_authenticated %}
              <div class="btn-group dropstart mx-1">
                <button type="button" class="btn btn-outline-dark dropdown-toggle btn-sm" data-bs-toggle="dropdown" aria-expanded="false">{{ user.username }}</button>
                <ul class="dropdown-menu">
                  <li>
                    <form action="{% url 'logout' %}" method="POST">
                      {% csrf_token %}
                      <button class="dropdown-item btn border-0"><i class="fas fa-sign-out-alt"></i> Cerrar sesion</button>
                    </form>
                  </li>
                </ul>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      {% block content %}

      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

users/templates/users/login.html
<form action="{% url 'login' %}" method="POST">
  {{ form.as_p }}
  <button>Login</button>
</form>

users/templates/users/register.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Coffee Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/fontawesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
    <style>
      .full-height {
        height: 100vh;
      }
      
      .centered {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
      }
      
      .no-scrollbar {
        overflow: hidden;
      }
      
      .background-image {
        width: 100%;
        height: 100%;
        object-fit: cover;
      }
      
      .responsive-logo {
        max-width: 100%;
        height: auto;
      }
    </style>
  </head>
  <body class="bg-light">
    <div class="container-fluid full-height">
      <div class="row no-gutters full-height">
        <div class="col-12 col-lg-6 d-none d-lg-block px-0">
          <img src="https://t1.gstatic.com/licensed-image?q=tbn:ANd9GcTuDKXbkn3GeIZJJOodadOiGxwsCP6KWCRAvtBCf_eFNowUrFmuaNz7j5UrV7K7nHgr" alt="Background" class="background-image" />
        </div>
        <div class="col-12 col-lg-6 d-flex justify-content-center align-items-center px-0">
          <div class="col-10 col-sm-7 col-lg-8 col-xl-7 col-xxl-6">
            <div class="card shadow-sm">
              <div class="card-body">
                <div class="col-12">
                  <form  method="POST">
                    {% csrf_token %}
                    <div class="row g-4">
                      <div class="col-12 text-center">
                        <i class="fa-solid fa-mug-hot fa-5x"></i>
                      </div>
                      <div class="col-12">{{ form|crispy }}</div>
                      <div class="col-12 d-grid mb-2">
                        <button class="btn btn-dark mb-2" type="submit">Crear cuenta</button>
                        <a class="btn btn-dark" type="submit" href="{% url "login" %}">Regresar</a>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>